# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Karat < Formula
  desc "Terminal UI for Apache Kafka"
  homepage "https://github.com/uraniumdawn/karat"
  version "0.3.0"
  license "MIT"

  depends_on "librdkafka"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/uraniumdawn/karat/releases/download/v0.3.0/karat_Darwin_x86_64.tar.gz"
    sha256 "cc32d83b2f64dfa9e3ef68ddc8f79bb423d81bedb9ec26a3bd954b7854a376d4"

    define_method(:install) do
      bin.install "karat"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/uraniumdawn/karat/releases/download/v0.3.0/karat_Darwin_arm64.tar.gz"
    sha256 "e07b2bb83d8bba47b169717a4577f197ee93e5e510fc6013fbf3a8f3f3d1f568"

    define_method(:install) do
      bin.install "karat"
    end
  end

  test do
    system "#{bin}/karat", "--version"
  end
end
